sudo: false
language: node_js
python:
- '2.7'
node_js:
- '0.10'
addons:
  sauce_connect: true
env:
- RUN_TEST=test-api
- RUN_TEST=test-client
- RUN_TEST=test-lib
script:
- make $RUN_TEST
cache:
  directories:
  - api/node_modules
  - client/node_modules
  - lib/node_modules
